city_demo:
  path: city/demo
  methods: [GET]
  defaults:
    _controller: 'Citylist\Controller\CitylistController::demoAction'
    # _disable_module_prefix: true

city_create:
  path: city/create
  methods: [GET, POST]
  defaults:
    _controller: 'Citylist\Controller\CitylistController::createAction'
    _disable_module_prefix: true

city_list:
  path: city/list
  methods: [GET]
  defaults:
    _controller: 'Citylist\Controller\CitylistController::listAction'
    # _disable_module_prefix: true
    _legacy_controller: AdminCityList

city_delete:
  path: city/delete/{id}
  methods: [GET]
  defaults:
    _controller: 'Citylist\Controller\CitylistController::deleteAction'
    # _disable_module_prefix: true

city_update:
  path: city/update/{id}
  methods: [GET, POST]
  defaults:
    _controller: 'Citylist\Controller\CitylistController::updateAction'
    # _disable_module_prefix: true



# City List controller Route
city_shipping_demo:
  path: city/shipping/demo
  methods: [GET]
  defaults:
    _controller: 'Citylist\Controller\CityListShippingController::demoAction'
    # _disable_module_prefix: true
  
city_shipping_create:
  path: city/shipping/create
  methods: [GET, POST]
  defaults:
    _controller: 'Citylist\Controller\CityListShippingController::createAction'
    _disable_module_prefix: true