city_demo:
  path: city/demo
  methods: [GET]
  defaults:
    _controller: 'Tntrunkscity\Controller\TntrunkscityController::demoAction'
    # _disable_module_prefix: true

city_create:
  path: city/create
  methods: [GET, POST]
  defaults:
    _controller: 'Tntrunkscity\Controller\TntrunkscityController::createAction'
    # _disable_module_prefix: true

city_list:
  path: city/list
  methods: [GET]
  defaults:
    _controller: 'Tntrunkscity\Controller\TntrunkscityController::listAction'
    # _disable_module_prefix: true

city_delete:
  path: city/delete/{id}
  methods: [GET]
  defaults:
    _controller: 'Tntrunkscity\Controller\TntrunkscityController::deleteAction'
    # _disable_module_prefix: true

city_edit:
  path: city/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Tntrunkscity\Controller\TntrunkscityController::editAction'
    # _disable_module_prefix: true
